name: crypto_book
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: ^1.0.3
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  http: ^0.13.4
  intl: ^0.17.0
  kiwi: ^3.0.0
  dropdown_plus: ^0.0.9
  class_to_map: ^0.0.1
  syncfusion_flutter_charts: ^19.3.44+1
  url_launcher: ^6.0.12

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  kiwi_generator: ^3.0.1

flutter:
  uses-material-design: true
